### ISSUE TITLE
Inline Comments

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#210]
GFM Allows inline HTML-Style comments, but these are not honored by Hyperbook.
Oh, and Blockquotes aren't rendered properly: https://hyperbook.openpatch.org/markdown-reference#blockquotes

**Comment by mikebarkmin** [comment]
I  think GFM does not have anything specific for comments, but GitHib for example allows to use raw HTML code in markdown. Currently in hyperbook this is not allowed. There are three options in my opionon:

1. allow HTML code
2. create a new directive for comments

I am not keen on allowing HTML code since I will not have control over the style and can not ensure custom HTML in the future, because I do not know what is used out there.

Directives for inline and block comments might therefore be better. They also have another benefit, I can just ignore them when the hyperbook is build. Thus comments live only in the raw markdown files, but not in the HTML files.

**Comment by mikebarkmin** [comment]
I will take a look at blockqoutes.

**Comment by mikebarkmin** [comment]
I thought about it a bit more and search how markdown comments can be handled. I think the best "native" way is described here: https://www.jamestharpe.com/markdown-comments/ and looks like this:

```
[]: # (This is a comment)
[]: # "And this is a comment"
[]: # 'Also this is a comment'
[//]: # (Yet another comment)
[comment]: # (Still another comment)
```

For the moment, I would suggest using this, since it is compatible with all markdown flavors and does not require a new syntax element. I will add a paragraph about comments to the documentation.

**Comment by xeruf** [comment]
interesting, thank you :)
