### ISSUE TITLE
PlantUML diagrams?

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#488]
I am a bit torn, I think PlantUML allows more detailed customizations: https://plantuml.com/
But overall Mermaid seems pretty good too.

So just offering this as an option to debate for now.

**Comment by mikebarkmin** [comment]
PlantUML is a great alternative to Mermaid and possible a even richer one. But PlantUML diagrams can only be generated server-side. This means we need to generate the diagrams when building the hyperbook. Mermaid on the onther currently works to rendering the diagrams on the client. So this would introduce another build step, but it can also open the gate for other server-side rendered applications like Graphviz.

We could also make use of https://kroki.io/. But this would mean that Hyperbook would need a network connection to render those diagrams. This is not my preferred way, since I am trying to make hyperbook work even in offline scenarios.

**Comment by mikebarkmin** [comment]
Implemented in #822
