### ISSUE TITLE
Support for HTML snippets

### ISSUE THREAD

**Issue by jneug** [openpatch/hyperbook#854]
I think the flexibility of the system would greatly benefit from allowing the use of custom HTML code for creating new elements.

I can think of two ways to support this:
1. Allow the use of `.html.hbs` files as snippets, that contain HTML rather than Markdown.
2. Add a directive `:::html` that can be used anywhere and just renders its content as plain HTML.

Example:
```md
:::html
<div class="box">
My content in a box.
</div>
:::
```

**Comment by mikebarkmin** [comment]
Or we can allow HTML to be used.

**Comment by jneug** [comment]
Sure. I assumed there was a reason to not do that in the first place.

**Comment by mikebarkmin** [comment]
Maybe supporting MDX would be even better.

**Comment by mikebarkmin** [comment]
There will be a new option for the hyperbook.config in the next release. It will be called: allowDangerousHtml. This allows to use HTML everywhere. It is called dangerous, because I can not guarantee compatibility with future releases. For example if you add a div container with class "super-awesome" and I later add an element with the same class, but style it differently, your styling might look off.
